#!/bin/bash

set -e -u
export PIPELINE=$1
export TARGET=c2c

fly -t $TARGET \
  set-pipeline -p "${PIPELINE}" \
  -c "${HOME}"/workspace/pcf-networking-ci/pipelines/"${PIPELINE}".yml \
  -l "${HOME}"/workspace/pcf-networking-deployments/pipeline-credentials.yml
